name: cyoap_core
description: CYOAP Project's core library
version: 4.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: any
  json_annotation: any
  js: any
  meta: any
  petitparser: ^6.0.2

dev_dependencies:
  freezed: ^2.2.0
  build_runner: any
  json_serializable: any
  lints: ^3.0.0
  test: ^1.16.0
