name: cyoap_core
description: CYOAP Project's core library
version: 4.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  freezed_annotation: any
  json_annotation: any
  js: any
  meta: any
  petitparser: ^6.0.2

dev_dependencies:
  freezed: ^3.1.0
  build_runner: ^2.5.4
  json_serializable: any
  lints: ^6.0.0
  test: ^1.16.0
