name: cyoap_core
description: A sample command-line application.
version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  freezed_annotation: any
  json_annotation: any
  js: any
  meta: any

dev_dependencies:
  freezed: 2.1.0+1
  build_runner: any
  json_serializable: any
  lints: ^2.0.0
  test: ^1.16.0
